### ISSUE TITLE
Download for 2015 not possible

### ISSUE THREAD

**Issue by HolgerJeromin** [vladeck/TSLint#1]
Searching for [your name](https://marketplace.visualstudio.com/search?term=publisher%3A"Vladimir%20Đokić") has only the 2017 extension. The [correct link](https://marketplace.visualstudio.com/items?itemName=vladeck.TSLint2015) asks for a ms login and after that gives 
![image](https://cloud.githubusercontent.com/assets/2410353/26643912/36f865d6-4633-11e7-8539-c2f8b103471f.png)

**Comment by vladimir-djokic** [comment]
I can confirm that the link is not working yet. It could be that the servers have not "picked up" the extension yet. Best we can do at this moment is wait an hour or two. If the problem persists after that time, I'll investigate further.

**Comment by vladimir-djokic** [comment]
It appears that the link is working. Please try now.

**Comment by vladimir-djokic** [comment]
@HolgerJeromin I'll close this, as links are available now. If you have any further issues with TSLint, don't hesitate to submit them.

**Comment by HolgerJeromin** [comment]
I have installed the extension. Thanks a lot! I will test it the next days.
