### ISSUE TITLE
No Ctrl+Space to fix the error

### ISSUE THREAD

**Issue by jvutukur** [vladeck/TSLint#12]
Also Error should be removed after changing content of file. As of now after making changes to file content still shows error.

Errors are gone when file is saved. Errors should go even if i dont save file.

**Comment by vladimir-djokic** [comment]
This extensions works as described on the front page: on `.ts` file **open** or **save** operation, locally installed `tslint` is executed upon that file. What you are requesting is, unfortunately, out of scope for this project.
