### ISSUE TITLE
Visual Studio crashes on saving .ts files

### ISSUE THREAD

**Issue by Devvox93** [vladeck/TSLint#13]
When saving .ts files, the cursor shows loading, then Visual Studio is not responding and after a few seconds in a new window it says "Visual Studio has stopped working" with Debug/Restart buttons.

*removed version info*

I don't know how to describe this any clearer.
If someone knows how I can find and provide more info about the crash, I'll be happy to post that as well.
I'll use VS Code in the meantime.
So weird that the full version doesn't have awesome linting integration...

**Comment by Devvox93** [comment]
Update: The problem was I was using Folder View without a solution/project.
When in a solution/project the extension works as intended.
Maybe this update will help some future users.

**Comment by akki-jat** [comment]
I am facing the same problem.

**Comment by vladimir-djokic** [comment]
@akki-jat 0.5.1 is up and should fix this issue - crashing VS when project is open as folder.
