### ISSUE TITLE
Linting .js files as well as .ts

### ISSUE THREAD

**Issue by RobPierce** [vladeck/TSLint#14]
I'm seeing [tslint] errors showing up when I open a .js javascript file as well as when editing .ts - I'm guessing it is not meant to be doing this and it is a bug?

**Comment by vladimir-djokic** [comment]
Could be, need more info.

**Comment by RobPierce** [comment]
I've got a VS2017 solution and the web project has both angularjs apps (with .js files) and angular apps (with .ts files) As well as showing taking errors when I have a .ts file open (which is awesome - thank you!), when I have a .js file open it is also applying the taking rules and showing the errors in the editor even though the tslint rules shouldn't apply to .js files?

**Comment by vladimir-djokic** [comment]
Can you provide me with a screenshot of the **Error Panel**? You can blur out the names of the files and such. This extension should not lint `.js` files, so my first hunch is that either **VS** or some other extensions is doing it.

**Comment by RobPierce** [comment]
Here's a screenshot of some of the errors showing up on js files:

![image](https://user-images.githubusercontent.com/6616428/36663349-31859788-1ad9-11e8-9ead-43a9ee346fee.png)

**Comment by vladimir-djokic** [comment]
@RobPierce Just uploaded a new version. Please test it and let me know if the issue is resolved on your end as well.

**Comment by RobPierce** [comment]
Perfect - now working as expected - many thanks!!!
