### ISSUE TITLE
No support for Vue single file components

### ISSUE THREAD

**Issue by hextraza** [vladeck/TSLint#17]
Since this plugin is only run on .ts files, there is no support for [Vue single file components](https://vuejs.org/v2/guide/single-file-components.html), since these end in .vue, even though the code in these components can be implemented in TypeScript.

It would be nice if this plugin could parse .vue files/look for a <script lang="ts"> and run the linter on that section of the code, or implement some other solution to this. It seems like there is [some support](https://github.com/palantir/tslint/issues/2099) for this directly in tslint already, but I'm not sure of the specifics.

**Comment by vladimir-djokic** [comment]
I agree that it would be nice, but this extension executes `tslint` in the background and as such is limited to the functionality that `tslint` provides. I took a glimpse at the links you provided and there is no actual support for `.vue` files - there are workarounds that are out of scope of `tslint` itself (`webpack` and friends...)
