### ISSUE TITLE
Analyse all files on build

### ISSUE THREAD

**Issue by 304NotModified** [vladeck/TSLint#5]
I like to have the TS linter errors in the VS error list when building.

Is this possible with this plugin? I can't get it working (VS2017.2)

**Comment by vladimir-djokic** [comment]
All **tslint** rules configured to be reported as **errors** should show in Visual Studio **Error List** when `.ts` file is opened/saved.

At the moment, extension does not provide functionality to lint all TypeScript files in solution/project when executing build. It is something that can be investigated for future versions...

**Comment by 304NotModified** [comment]
It is the idea to combine this plugin with https://github.com/Pablissimo/SonarTsPlugin, and so this is intended behavior?

**Comment by vladimir-djokic** [comment]
I tried being clear in the `README.md` about **what** and **how**. Analyzing **entire** project/solution on build (or any other) event was **NEVER** the goal (nor did I wrote somewhere that is it how this extension works). Thought it is something that might come in later versions, it is not something I'm actively working on.

On the other hand, I will gladly review and (possibly merge) any **PR** implementing this feature.

**Comment by 304NotModified** [comment]
Oops,

I meant https://github.com/rich-newman/typescript-analyzer, not SonarTsPlugin.

Anyway, it doens't work well as of course we get the errors twice in the error list.



> I tried being clear in the README.md about what and how.

I was thinking it was a replacement of https://github.com/rich-newman/typescript-analyzer, but it wasn't

**Comment by vladimir-djokic** [comment]
Closed issue as it is out of scope for this project.
