### ISSUE TITLE
Some files are not analyzed

### ISSUE THREAD

**Issue by mogwai1** [vladeck/TSLint#9]
Some files are not analyzed by extension.
Here is the example of such ts file. What's wrong with it?

[test-file.ts.txt](https://github.com/vladeck/TSLint/files/1542597/test-file.ts.txt)

Manual analyze with tslint from cmd works fine and shows a lot of issues. But there is no highlighting in studio editor at all.

My tslist.json extremely simple:
> {
  "extends": [
    "tslint:recommended"
  ],
  "jsRules": {},
  "rules": {}
}

**Comment by vladimir-djokic** [comment]
By default, this extension works only for files that end in `.ts`. Your file ends in `.txt`. Try renaming that file to `test-file.ts` and see if it solves the problem you are facing?

**Comment by mogwai1** [comment]
I renamed file just because of github upload limitation. In studio I use it with .ts extension, of course.

**Comment by vladimir-djokic** [comment]
Thank you, I have identified the issue and will have it resolved by the end of the day. It should also resolve some performance issues with this extension. Stay tuned!

**Comment by mogwai1** [comment]
Great, it works now. Thank you.
